--- 

- name: Ensure git is available
  package: name={{item}} state=present
  with_items:
    - git

- name: git clone lab
  git:
    repo: https://gitlab.com/2020-summit-labs/containerizing-applications.git
    dest: /home/lab-user/containerizing-applications




